#ifndef XMLSCHEMA_H
#define XMLSCHEMA_H

/// the xml template schema
/// will be able to program it
/// in the future
/// \brief XSD
///
static const char XSD[] =
        "<?xml version=\"1.0\"?>"
        "<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">"
        "<xs:element name=\"Config\">"
        "<xs:complexType>"
        "<xs:sequence>"
            "<xs:element name=\"Voip\">"
            "<xs:complexType>"
            "<xs:sequence>"
                        "<xs:element name=\"SipRegistrar\">"
                            "<xs:complexType>"
                                "<xs:attribute name=\"url\" type=\"xs:string\" use=\"required\"/>"
                            "</xs:complexType>"
                        "</xs:element>"
                        "<xs:element name=\"SipTransport\">"
                            "<xs:complexType>"
                                "<xs:attribute name=\"type\" type=\"xs:string\" use=\"required\"/>"
                                "<xs:attribute name=\"port\" type=\"xs:positiveInteger\" use=\"required\"/>"
                                "<xs:attribute name=\"portRange\" type=\"xs:positiveInteger\" use=\"required\"/>"
                                "<xs:attribute name=\"qos\" type=\"xs:string\" use=\"required\"/>"
                            "</xs:complexType>"
                        "</xs:element>"
                        "<xs:element name=\"RtpTransport\">"
                            "<xs:complexType>"
                                "<xs:attribute name=\"type\" type=\"xs:string\" use=\"required\"/>"
                                "<xs:attribute name=\"port\" type=\"xs:positiveInteger\" use=\"required\"/>"
                                "<xs:attribute name=\"portRange\" type=\"xs:positiveInteger\" use=\"required\"/>"
                                "<xs:attribute name=\"qos\" type=\"xs:string\" use=\"required\"/>"
                            "</xs:complexType>"
                        "</xs:element>"
                        "<xs:element name=\"Media\">"
                            "<xs:complexType>"
                                "<xs:attribute name=\"audioCodec\" type=\"xs:string\" use=\"required\"/>"
                            "</xs:complexType>"
                        "</xs:element>"
                        "<xs:element name=\"Jitter\">"
                            "<xs:complexType>"
                                "<xs:attribute name=\"init\" type=\"xs:integer\" use=\"required\"/>"
                                "<xs:attribute name=\"max\" type=\"xs:integer\" use=\"required\"/>"
                                "<xs:attribute name=\"minPrefetch\" type=\"xs:integer\" use=\"required\"/>"
                                "<xs:attribute name=\"maxPrefetch\" type=\"xs:integer\" use=\"required\"/>"
                            "</xs:complexType>"
                        "</xs:element>"
            "</xs:sequence>"
            "</xs:complexType>"
            "</xs:element>"
                "<xs:element name=\"Audio\">"
                "<xs:complexType>"
                "<xs:sequence>"
                    "<xs:element name=\"Line1\">"
                    "<xs:complexType>"
                        "<xs:attribute name=\"capDevName\" type=\"xs:string\" use=\"required\"/>"
                        "<xs:attribute name=\"capLatency\" use=\"required\">"
                            "<xs:simpleType>"
                                "<xs:restriction base=\"xs:positiveInteger\">"
                                    "<xs:enumeration value=\"100\" />"
                                "</xs:restriction>"
                            "</xs:simpleType>"
                        "</xs:attribute>"
                        "<xs:attribute name=\"playDevName\" type=\"xs:string\" use=\"required\"/>"
                        "<xs:attribute name=\"playLatency\" type=\"xs:positiveInteger\" use=\"required\"/>"
                        "<xs:attribute name=\"clockRate\" use=\"required\">"
                            "<xs:simpleType>"
                                "<xs:restriction base=\"xs:integer\">"
                                    "<xs:enumeration value=\"8000\"/>"
                                    "<xs:enumeration value=\"16000\"/>"
                                    "<xs:enumeration value=\"32000\"/>"
                                "</xs:restriction>"
                            "</xs:simpleType>"
                        "</xs:attribute>"
                        "<xs:attribute name=\"frameTime\" use=\"required\">"
                            "<xs:simpleType>"
                                "<xs:restriction base=\"xs:integer\">"
                                    "<xs:enumeration value=\"10\"/>"
                                    "<xs:enumeration value=\"20\"/>"
                                "</xs:restriction>"
                            "</xs:simpleType>"
                        "</xs:attribute>"
                    "</xs:complexType>"
                    "</xs:element>"
                    "<xs:element name=\"Line2\"/>"
                "</xs:sequence>"
                "</xs:complexType>"
                "</xs:element>"
                "<xs:element name=\"Authentication\">"
                "<xs:complexType>"
                    "<xs:attribute name=\"method\" use=\"required\"/>"
                    "<xs:attribute name=\"password\" use=\"required\"/>"
                    "<xs:attribute name=\"staticCardId\"  use=\"required\"/>"
                "</xs:complexType>"
                "</xs:element>"
                "<xs:element name=\"RoleServer\">"
                "<xs:complexType>"
                    "<xs:attribute name=\"url\"  use=\"required\"/>"
                "</xs:complexType>"
                "</xs:element>"
                "<xs:element name=\"PTT\">"
                "<xs:complexType>"
                    "<xs:attribute name=\"footSwitch\" use=\"required\"/>"
                    "<xs:attribute name=\"line1\"  use=\"required\"/>"
                    "<xs:attribute name=\"line2\"  use=\"required\"/>"
                "</xs:complexType>"
                "</xs:element>"
                "<xs:element name=\"TScreen\"/>"
                "<xs:element name=\"Ui\"/>"
                "<xs:element name=\"EmergencyCall\"/>"
                "<xs:element name=\"Network\"/>"
                "<xs:element name=\"Beeper\"/>"
                "<xs:element name=\"Log\"/>"
                "<xs:element name=\"Phonebook\"/>"
        "</xs:sequence>"
        "</xs:complexType>"
        "</xs:element>"
        "</xs:schema>"
        ;


#endif // XMLSCHEMA_H
